package mapping;

public class DefaultMaps {
	
	public static final String defaultMapping = "0 - 64 50\n"
								  + "0 - 64 67\n"
								  + "0 - 64 72\n"
								  + "65 - 127 55\n"
								  + "65 - 127 64\n"
								  + "65 - 127 67\n";
	
	public static final String defaultOrgMapping = "states:\n"
												 + "0 0\n"
												 + "1 4\n"
												 + "2 7\n"
												 + "3 -4\n"
												 + "4 -7\n"
												 + "transitions:\n"
												 + "0 0 .2\n"
												 + "0 1 .3\n"
												 + "1 0 .4\n"
												 + "1 1 .1\n"
												 + "1 2 .1\n"
												 + "1 3 .2\n"
												 + "1 4 .2\n"
												 + "2 0 .5\n"
												 + "2 1 .1\n"
												 + "2 2 .1\n"
												 + "2 3 .1\n"
												 + "2 4 .2\n"
												 + "3 0 .2\n"
												 + "3 1 .2\n"
												 + "3 2 .2\n"
												 + "3 3 .2\n"
												 + "3 4 .2\n"
												 + "4 0 .1\n"
												 + "4 1 .6\n"
												 + "4 2 .1\n"
												 + "4 3 .1\n"
												 + "4 4 .1\n";
	
	public static final String defaultTimeMapping = "states:\n"
												  + "0 4\n"
												  + "1 2\n"
												  + "2 8\n"
												  + "3 16\n"
												  + "4 1\n"
												  + "transitions:\n"
												  + "0 0 .2\n"
												  + "0 1 .3\n"
												  + "0 2 .1\n"
												  + "0 3 .2\n"
												  + "0 4 .2\n"
												  + "1 0 .4\n"
												  + "1 1 .1\n"
												  + "1 2 .1\n"
												  + "1 3 .2\n"
												  + "1 4 .2\n"
												  + "2 0 .5\n"
												  + "2 1 .1\n"
												  + "2 2 .1\n"
												  + "2 3 .1\n"
												  + "2 4 .2\n"
												  + "3 0 .2\n"
												  + "3 1 .2\n"
												  + "3 2 .2\n"
												  + "3 3 .2\n"
												  + "3 4 .2\n"
												  + "4 0 .1\n"
												  + "4 1 .6\n"
												  + "4 2 .1\n"
												  + "4 3 .1\n"
												  + "4 4 .1\n";
	
	public static final String defaultVelMapping = "states:\n"
												 + "0 96\n"
												 + "1 116\n"
												 + "2 80\n"
												 + "3 60\n"
												 + "4 48\n"
												 + "transitions:\n"
												 + "0 0 .2\n"
												 + "0 1 .3\n"
												 + "0 2 .1\n"
												 + "0 3 .2\n"
												 + "0 4 .2\n"
												 + "1 0 .4\n"
												 + "1 1 .1\n"
												 + "1 2 .1\n"
												 + "1 3 .2\n"
												 + "1 4 .2\n"
												 + "2 0 .5\n"
												 + "2 1 .1\n"
												 + "2 2 .1\n"
												 + "2 3 .1\n"
												 + "2 4 .2\n"
												 + "3 0 .2\n"
												 + "3 1 .2\n"
												 + "3 2 .2\n"
												 + "3 3 .2\n"
												 + "3 4 .2\n"
												 + "4 0 .1\n"
												 + "4 1 .6\n"
												 + "4 2 .1\n"
												 + "4 3 .1\n"
												 + "4 4 .1\n";
}
